restrictedRepos:
  exclude:
    - .github

configvalidators:
  - plugin: collaborators
    error: |
      `Admin cannot be assigned to collaborators`
    script: |
      console.log(`baseConfig ${JSON.stringify(baseconfig)}`)
      return baseconfig.permission != 'admin'
